server:
  port: 8082
  address: 127.0.0.1
    
spring:
  jdbc:
    #driver-class-name: com.mysql.jdbc.Driver
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    # 使用druid数据源
    pgmaxActive: 20
    pginitialSize: 5
    pgminIdle: 2
    maxActive: 500
    initialSize: 20
    minIdle: 20
    maxWait: 3000
    timeBetweenEvictionRunsMillis: 60000
    removeAbandoned: true
    removeAbandonedTimeout: 120
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    filters: stat
    
#redis单服务配置
#  redis:
#    host: localhost
#    port: 6379
#    password: 123456
#    database: 1
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 500
#      min-idle: 0
#      timeout: 0    
      
#redis集群配置   

jedisPool:
  maxTotal: 2048
  maxIdle: 200
  minIdle: 10
  numTestsPerEvictionRun: 1024
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: -1
  softMinEvictableIdleTimeMillis: 10000
  maxWaitMillis: 1500
  testOnBorrow: true
  testWhileIdle: true
  testOnReturn: false
  blockWhenExhausted: false

redis:
  clusterNodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
  clusterTimeout: 20000
  maxRedirects: 8
  normalExpire: 86400
